package com.staricka.adventofcode2023.days

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals

class Day11Test {
    val day = Day11(oldMultiplier = 10)

    @Test
    fun part1() {
        assertEquals(374, day.part1("""
            ...#......
            .......#..
            #.........
            ..........
            ......#...
            .#........
            .........#
            ..........
            .......#..
            #...#.....
        """.trimIndent()))
    }

    @Test
    fun part2() {
        assertEquals(1030L, day.part2("""
            ...#......
            .......#..
            #.........
            ..........
            ......#...
            .#........
            .........#
            ..........
            .......#..
            #...#.....
        """.trimIndent()))
    }
}